[project]
name = "order-processing"
version = "0.1.0"
description = "Order Processing Service"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.136.3",
    "pika>=1.4.1",
    "psycopg[binary]>=3.3.4",
    "ruff>=0.15.15",
    "sqlalchemy>=2.0.50",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]
